# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artificialdata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61rtificialdata.proto\x12\x0e\x61rtificialdata\"=\n\x0fsequenceRequest\x12\x10\n\x08slot_idx\x18\x01 \x01(\x05\x12\x18\n\x10proportions_json\x18\x02 \x01(\t\"\x1c\n\x08sayonara\x12\x10\n\x08slot_idx\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"\xd7\x02\n\rsequenceReply\x12\x12\n\nnum_frames\x18\x01 \x01(\x05\x12\x15\n\rwristpose_csv\x18\x02 \x01(\t\x12\x15\n\relbowpose_csv\x18\x03 \x01(\t\x12\x16\n\x0e\x66ingerpose_csv\x18\x04 \x01(\t\x12\x1a\n\x12use_exr_background\x18\x05 \x01(\x08\x12\x14\n\x0crender_alpha\x18\x06 \x01(\x08\x12\x16\n\x0ehand_poses_csv\x18\x07 \x01(\t\x12\x17\n\x0f\x63\x61mera_info_csv\x18\x08 \x01(\t\x12\x19\n\x11valid_samples_csv\x18\t \x01(\t\x12\"\n\x1aoutput_color_images_folder\x18\n \x01(\t\x12\"\n\x1aoutput_alpha_images_folder\x18\x0b \x01(\t\x12\x13\n\x0b\x64ont_render\x18\x0c \x01(\x08\x12\x11\n\tframerate\x18\r \x01(\x02\x32\xa3\x01\n\x13\x41rtificialDataNexus\x12P\n\x0e\x61skForSequence\x12\x1f.artificialdata.sequenceRequest\x1a\x1d.artificialdata.sequenceReply\x12:\n\x07goodbye\x12\x18.artificialdata.sayonara\x1a\x15.artificialdata.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artificialdata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCEREQUEST._serialized_start=40
  _SEQUENCEREQUEST._serialized_end=101
  _SAYONARA._serialized_start=103
  _SAYONARA._serialized_end=131
  _EMPTY._serialized_start=133
  _EMPTY._serialized_end=140
  _SEQUENCEREPLY._serialized_start=143
  _SEQUENCEREPLY._serialized_end=486
  _ARTIFICIALDATANEXUS._serialized_start=489
  _ARTIFICIALDATANEXUS._serialized_end=652
# @@protoc_insertion_point(module_scope)
