# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artificialdata_loader.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61rtificialdata_loader.proto\x12\x15\x61rtificialdata_loader\"\x15\n\x13numSequencesRequest\" \n\x11numSequencesReply\x12\x0b\n\x03num\x18\x01 \x01(\x04\"8\n\rsampleRequest\x12\x14\n\x0csequence_idx\x18\x01 \x01(\x04\x12\x11\n\tframe_idx\x18\x02 \x01(\x04\"\xe5\x04\n\x0bsampleReply\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x1a\n\x12image_width_height\x18\x02 \x01(\x05\x12\x19\n\x11keypoints_gt_px_x\x18\x03 \x03(\x02\x12\x19\n\x11keypoints_gt_px_y\x18\x04 \x03(\x02\x12%\n\x1dkeypoints_gt_depth_rel_midpxm\x18\x05 \x03(\x02\x12%\n\x1dkeypoints_pose_predicted_px_x\x18\x06 \x03(\x02\x12%\n\x1dkeypoints_pose_predicted_px_y\x18\x07 \x03(\x02\x12\x31\n)keypoints_pose_predicted_depth_rel_midpxm\x18\x08 \x03(\x02\x12\x1c\n\x14stereographic_radius\x18\t \x01(\x02\x12\x17\n\x0fhomothety_scale\x18\n \x01(\x02\x12\x1d\n\x15move_overall_variance\x18\x0b \x01(\x02\x12\x1f\n\x17move_per_joint_variance\x18\x0c \x01(\x02\x12\x15\n\rsg_expand_val\x18\x0e \x01(\x02\x12\x17\n\x0fprediction_type\x18\x10 \x01(\x05\x12\'\n\x1f\x65lbow_direction_px_x_normalized\x18\x12 \x01(\x02\x12\'\n\x1f\x65lbow_direction_px_y_normalized\x18\x13 \x01(\x02\x12!\n\x19\x64otprod_elbowdir_wristloc\x18\x14 \x01(\x02\x12\x12\n\nalpha_data\x18\x16 \x01(\x0c\x12\x18\n\x10\x61lpha_data_valid\x18\x17 \x01(\x08\x32\xdc\x01\n\x14\x41rtificialDataLoader\x12X\n\x0c\x61skForSample\x12$.artificialdata_loader.sampleRequest\x1a\".artificialdata_loader.sampleReply\x12j\n\x12\x61skForNumSequences\x12*.artificialdata_loader.numSequencesRequest\x1a(.artificialdata_loader.numSequencesReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artificialdata_loader_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMSEQUENCESREQUEST._serialized_start=54
  _NUMSEQUENCESREQUEST._serialized_end=75
  _NUMSEQUENCESREPLY._serialized_start=77
  _NUMSEQUENCESREPLY._serialized_end=109
  _SAMPLEREQUEST._serialized_start=111
  _SAMPLEREQUEST._serialized_end=167
  _SAMPLEREPLY._serialized_start=170
  _SAMPLEREPLY._serialized_end=783
  _ARTIFICIALDATALOADER._serialized_start=786
  _ARTIFICIALDATALOADER._serialized_end=1006
# @@protoc_insertion_point(module_scope)
