# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import artificialdata_loader_pb2 as artificialdata__loader__pb2


class ArtificialDataLoaderStub(object):
    """The string reversal service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.askForSample = channel.unary_unary(
                '/artificialdata_loader.ArtificialDataLoader/askForSample',
                request_serializer=artificialdata__loader__pb2.sampleRequest.SerializeToString,
                response_deserializer=artificialdata__loader__pb2.sampleReply.FromString,
                )
        self.askForNumSequences = channel.unary_unary(
                '/artificialdata_loader.ArtificialDataLoader/askForNumSequences',
                request_serializer=artificialdata__loader__pb2.numSequencesRequest.SerializeToString,
                response_deserializer=artificialdata__loader__pb2.numSequencesReply.FromString,
                )


class ArtificialDataLoaderServicer(object):
    """The string reversal service definition.
    """

    def askForSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def askForNumSequences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtificialDataLoaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'askForSample': grpc.unary_unary_rpc_method_handler(
                    servicer.askForSample,
                    request_deserializer=artificialdata__loader__pb2.sampleRequest.FromString,
                    response_serializer=artificialdata__loader__pb2.sampleReply.SerializeToString,
            ),
            'askForNumSequences': grpc.unary_unary_rpc_method_handler(
                    servicer.askForNumSequences,
                    request_deserializer=artificialdata__loader__pb2.numSequencesRequest.FromString,
                    response_serializer=artificialdata__loader__pb2.numSequencesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artificialdata_loader.ArtificialDataLoader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArtificialDataLoader(object):
    """The string reversal service definition.
    """

    @staticmethod
    def askForSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/artificialdata_loader.ArtificialDataLoader/askForSample',
            artificialdata__loader__pb2.sampleRequest.SerializeToString,
            artificialdata__loader__pb2.sampleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def askForNumSequences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/artificialdata_loader.ArtificialDataLoader/askForNumSequences',
            artificialdata__loader__pb2.numSequencesRequest.SerializeToString,
            artificialdata__loader__pb2.numSequencesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
